name = "MeshArrays"
uuid = "cb8c808f-1acf-59a3-9d2b-6e38d009f683"
authors = ["gaelforget <gforget@mit.edu>"]
version = "0.3.0"

[deps]
CatViews = "81a5f4ea-a946-549a-aa7e-2a7f63a27d31"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[extensions]
MeshArraysDownloadsExt = ["Downloads"]
MeshArraysGeoJSONExt = ["GeoJSON"]
MeshArraysJLD2Ext = ["JLD2"]
MeshArraysMakieExt = ["Makie"]
MeshArraysProjExt = ["Proj"]
MeshArraysShapefileExt = ["Shapefile"]
MeshArraysZipFileExt = ["ZipFile"]

[compat]
CatViews = "1.0"
Downloads = "1"
GeoJSON = "0.6, 0.7"
JLD2 = "0.4"
Makie = "0.19"
NearestNeighbors = "0.4"
Proj = "1"
Shapefile = "0.10"
Unitful = "1"
ZipFile = "0.10"
julia = "^1.9"
