name = "GCMFaces"
uuid = "28126448-9d44-11e8-08f5-e59c47736fcb"
authors = ["gaelforget <gforget@mit.edu>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
